replicaCount: 2

image:
  repository: docker.io/hannageorge/n01626469-nginx
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true        
  className: ""        
  annotations: {}
  hosts:
    - host: ""         
      paths:
        - path: /
          pathType: Prefix
  tls: []
