name: ci-build-and-push

on:
  push:
    branches: [ "main" ]
    paths:
      - "web/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/n01626469-nginx:v1
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/n01626469-nginx:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/n01626469-nginx:${{ github.sha }}
