name: ci-build-and-push
on:
  push:
    branches: [ "main" ]
    paths:
      - "web/**"
      - ".github/workflows/**"
env:
  IMAGE_NAME: "n01626469-nginx"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/n01626469-nginx:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/n01626469-nginx:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/n01626469-nginx:v1
